name: dgen_pyenv
dependencies:
- _license=1.1=py27_0
- alabaster=0.7.3=py27_0
- anaconda=2.3.0=np19py27_0
- appnope=0.1.0=py27_0
- argcomplete=0.8.9=py27_0
- babel=2.1.1=py27_0
- binstar=0.11.0=py27_0
- colorama=0.3.3=py27_0
- configobj=5.0.6=py27_0
- curl=7.43.0=0
- cython=0.22.1=py27_0
- cytoolz=0.7.3=py27_0
- decorator=4.0.4=py27_0
- docutils=0.12=py27_0
- freetype=2.5.2=2
- h5py=2.5.0=np19py27_3
- hdf5=1.8.15.1=1
- ipaddress=1.0.7=py27_0
- ipykernel=4.1.0=py27_0
- ipython=4.0.0=py27_1
- ipython-notebook=3.2.0=py27_0
- ipython-qtconsole=3.2.0=py27_0
- ipython_genutils=0.1.0=py27_0
- jedi=0.9.0=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter_client=4.1.1=py27_0
- jupyter_core=4.0.6=py27_0
- libpng=1.6.17=0
- libsodium=0.4.5=0
- markupsafe=0.23=py27_0
- mistune=0.7.1=py27_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.1=py27_0
- nltk=3.0.3=np19py27_0
- nose=1.3.7=py27_0
- numba=0.19.1=np19py27_0
- numexpr=2.4.3=np19py27_0
- numpy=1.9.2=py27_0
- openpyxl=1.8.5=py27_0
- openssl=1.0.1k=1
- pandas=0.16.2=np19py27_0
- path.py=8.1.2=py27_0
- pep8=1.6.2=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- ply=3.6=py27_0
- psutil=3.2.2=py27_0
- psycopg2=2.6=py27_1
- py=1.4.27=py27_0
- pycurl=7.19.5.1=py27_2
- pyflakes=1.0.0=py27_0
- pygments=2.0.2=py27_0
- pyopenssl=0.15.1=py27_1
- pyqt=4.11.4=py27_0
- pysal=1.6.0=np18py27_1
- pytables=3.2.0=np19py27_0
- pytest=2.7.1=py27_0
- python=2.7.10=1
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.6=py27_0
- pyyaml=3.11=py27_1
- pyzmq=14.7.0=py27_0
- qt=4.8.7=1
- qtconsole=4.1.0=py27_0
- readline=6.2=2
- requests=2.7.0=py27_0
- rope=0.9.4=py27_1
- runipy=0.1.3=py27_0
- scikit-image=0.11.3=np19py27_0
- scikit-learn=0.16.1=np19py27_0
- scipy=0.15.1=np19py27_0
- setuptools=18.4=py27_0
- simplegeneric=0.8.1=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.0=py27_0
- sphinx=1.3.1=py27_0
- sphinx_rtd_theme=0.1.7=py27_0
- spyder=2.3.7=py27_1
- spyder-app=2.3.5.2=py27_0
- sqlalchemy=1.0.5=py27_0
- sqlite=3.8.4.1=1
- sqlparse=0.1.15=py27_0
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np19py27_0
- tk=8.5.18=0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- xlrd=0.9.3=py27_0
- xlsxwriter=0.7.3=py27_0
- xlwings=0.3.5=py27_0
- xlwt=1.0.0=py27_0
- yaml=0.1.6=0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-core==4.0.6
  - sphinx-rtd-theme==0.1.7
  - tables==3.2.0
  - colorlog
